{% set name = "launchdarkly-server-sdk" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/launchdarkly-server-sdk-{{ version }}.tar.gz
  sha256: ee4af2e5949a43e4404a12fbfd5b419b48f94fdb72d867ad0e8e6f8e7427dd08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - certifi >=2018.4.16
    - expiringdict >=1.1.4
    - pyrfc3339 >=1.0
    - python >=3.6
    - semver >=2.10.2
    - urllib3 >=1.22.0,<3

test:
  imports:
    - ldclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/launchdarkly/python-server-sdk
  summary: LaunchDarkly SDK for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
