{% set name = "launchdarkly-server-sdk" %}
{% set version = "9.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 150e29656cb8c506d1967f3c59e62b69310d345ec27217640a6146dd1db5d250

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - launchdarkly-eventsource >=1.2.4,<2.0.0
    - certifi >=2018.4.16
    - expiringdict >=1.1.4
    - pyrfc3339 >=1.0
    - python >={{ python_min }}
    - semver >=2.10.2
    - urllib3 >=1.26.0,<3

test:
  imports:
    - ldclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/launchdarkly/python-server-sdk
  summary: LaunchDarkly SDK for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
