{% set name = "launchdarkly-server-sdk" %}
{% set version = "9.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 10a39a22e1d9feb31c8586c19d03167c3d8e1ac277c6adc0864032a0c2e1c62e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.8
  run:
    - launchdarkly-eventsource >=1.1.0,<2.0.0
    - certifi >=2018.4.16
    - expiringdict >=1.1.4
    - pyrfc3339 >=1.0
    - python >=3.8
    - semver >=2.10.2
    - urllib3 >=1.26.0,<3

test:
  imports:
    - ldclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/launchdarkly/python-server-sdk
  summary: LaunchDarkly SDK for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
