{% set name = "launchdarkly-server-sdk" %}
{% set version = "9.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e887b3532d731ba90683da41e3682fa366267beae8f12a35223957ad5b83e694

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - hatchling
    - python {{ python_min }}
  run:
    - launchdarkly-eventsource >=1.7.2,<2.0.0
    - certifi >=2018.4.16
    - expiringdict >=1.1.4
    - pyrfc3339 >=1.0
    - python >={{ python_min }}
    - semver >=2.10.2
    - urllib3 >=1.26.0,<3

test:
  imports:
    - ldclient
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/launchdarkly/python-server-sdk
  summary: LaunchDarkly SDK for Python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xhochy
